# Generated by Django 4.2 on 2023-06-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventashop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
