# Generated by Django 4.2 on 2023-04-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventashop', '0002_alter_user_managers_remove_user_username_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='Ventalis', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_number',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
