# Generated by Django 4.2 on 2023-04-24 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventashop', '0003_user_company_user_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='employee_reg',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
