# Generated by Django 4.2 on 2023-04-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventashop', '0004_lineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='lineitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ventashop.cart'),
        ),
    ]
