# Generated by Django 4.2 on 2023-04-21 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventashop', '0004_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventashop.customeraccount'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='customer_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ventashop.customeraccount'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
