# Generated by Django 4.2 on 2023-04-21 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventashop', '0005_cart_customer_account_conversation_customer_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ventashop.customeraccount'),
        ),
    ]
