# Generated by Django 4.2 on 2023-04-26 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventashop', '0005_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
