# Generated by Django 4.2 on 2023-04-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventashop', '0007_alter_cart_total_price_alter_lineitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventashop.cart'),
        ),
    ]
