# Generated by Django 4.2 on 2023-04-15 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventashop', '0009_alter_lineitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NT', 'Non traitée'), ('CT', 'En cours de traitement'), ('AA', "En attente d'approvisionnement"), ('PE', "En préparation à l'expédition"), ('AP', 'En attente de paiement'), ('EX', 'Expédiée'), ('TA', 'Traitée'), ('AN', 'Annulée')], default='NT', max_length=2)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('ref_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventashop.order')),
            ],
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventashop.order'),
        ),
    ]
